### ISSUE TITLE
How to install libero plug-In in iDempiere ?

### ISSUE THREAD

**Issue by thiru506** [pshepetko/org.idempiere.mfg#2]
I have installed idempiere by using [hengsin](https://github.com/hengsin/idempiere-dev-setup) 
Now I want to install Libero plug-in , can you please provide detail document or process..

@pshepetko

Thanks

**Comment by pshepetko** [comment]
You can download the liberoMFG plugin for immediate use in your latest
iDempiere from https://github.com/pshepetko/org.idempiere.mfg/tree/master/downloads
In Apache Felix Web Console: 1) Install plugin 2) Select file 3) Install and Update
![image](https://user-images.githubusercontent.com/29797211/75144017-74381f00-56f6-11ea-979a-30507ee4e474.png)

**Comment by thiru506** [comment]
Thanks for reply...I did that successfully , status is showing installed but not changes to Active state..FYI am attaching scree...please help to install
![Screenshot from 2020-02-24 16-31-12](https://user-images.githubusercontent.com/26535193/75147501-782e6600-5723-11ea-8b81-67797b180f1c.png)

**Comment by pshepetko** [comment]
Thanks for the log, 
which show that you had error because developers  renamed jfree.chart library in core of  iDempiere.
![image](https://user-images.githubusercontent.com/29797211/75187888-5648d980-574b-11ea-94ac-030066edcca1.png)

I fixed and updated plugin which you can download  for installing.
Give me ,pls,feedback about results.

**Comment by thiru506** [comment]
Thanks @pshepetko ..Now the plugin working fine , installed successfully..Status also get changed to Active...I am attaching successful scenario screens PFA...

Thank you so much for help... @pshepetko 
![Screenshot from 2020-02-25 10-51-13](https://user-images.githubusercontent.com/26535193/75217472-25a18800-57bd-11ea-8a2a-e6c0fca7624e.png)
![Screenshot from 2020-02-25 10-48-50](https://user-images.githubusercontent.com/26535193/75217479-276b4b80-57bd-11ea-9466-17cff576b807.png)
![Screenshot from 2020-02-25 10-45-36](https://user-images.githubusercontent.com/26535193/75217481-276b4b80-57bd-11ea-8bb4-f250b820cc9d.png)

**Comment by pshepetko** [comment]
**@thiru506** thank you for feedback!
