### ISSUE TITLE
Problem installing plugin Libero 7.1

### ISSUE THREAD

**Issue by solariv** [pshepetko/org.idempiere.mfg#4]
Hello! I want to install Libero but i have this error when im triying. Hope you can help me.

**Version of Idempiere:**

![image](https://user-images.githubusercontent.com/72880471/96639043-b6961800-12e6-11eb-83c7-3b20add8563e.png)

**Im doing this:**

![image](https://user-images.githubusercontent.com/72880471/96638947-8ea6b480-12e6-11eb-855b-48671d7fdbe4.png)

**Error in the web:** 

![error libero](https://user-images.githubusercontent.com/72880471/96638783-4f786380-12e6-11eb-9f7f-c34557063b1c.PNG)

**Error in the console:**

![image](https://user-images.githubusercontent.com/72880471/96638849-661eba80-12e6-11eb-866b-30a102206d7d.png)

**Comment by solariv** [comment]
I saw the error! I has de wrong jar. thanks!!

**Comment by pshepetko** [comment]
I checked this plugin on "Daily v7.1 (maintained) – this is the same as the version 7.1 below plus all stability fixes applied" version and i didn't have any installation errors.
